Fail the action if curl doesn't download anything
im-open/download-release-asset pull request #2
Opened 2021-11-05 00:41 UTC by mike-schenk

If curl is unable to download the file, `-f` should cause it to produce a non-zero exit code, causing the script to exit with a non-zero code so the action fails.
See https://www.mit.edu/afs.new/sipb/user/ssen/src/curl-7.11.1/docs/curl.html#-f--fail

2021-11-05 12:15 UTC, JosephDSchwartz approved these changes, later dismissed
Failing makes sense to me if no release is found. Otherwise I imagine it could be hard to diagnose problems with deployments.

2021-11-05 16:42 UTC, hpractv commented
@mike-schenk, are you able to merge these, or should I do that for you?

2021-11-11 15:26 UTC, danielle-casella-adams requested changes
The readme.md will need it's version bumped to v1.0.1

2021-11-12 15:01 UTC, danielle-casella-adams approved these changes

2021-11-12 15:02 UTC, merged

2021-11-15 22:26 UTC, mike-schenk commented
@danielle-casella-adams, will you add the v1.0.1 tag to this repo?